oms.env=DAILY
# 未使用 Redis 限制器时排除 Redis 自动装配，避免连接 localhost:6379 失败
# 若 concurrency.limiter-type=redis，请删除此行并配置 spring.data.redis.host 等

#单机：
#spring.data.redis.host=127.0.0.1
#spring.data.redis.port=6379
#spring.data.redis.password=
#
#哨兵（Sentinel）：
#spring.data.redis.sentinel.master=mymaster
#spring.data.redis.sentinel.nodes=host1:26379,host2:26379,host3:26379
#spring.data.redis.password=
#
#集群（Cluster）：
#spring.data.redis.cluster.nodes=host1:6379,host2:6379,host3:6379
#spring.data.redis.cluster.max-redirects=3

#spring.data.redis.jedis.pool.max-active=16
#spring.data.redis.jedis.pool.max-idle=8
#spring.data.redis.jedis.pool.min-idle=2
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

logging.config=classpath:logback-dev.xml

####### Database properties(Configure according to the the environment) #######
spring.datasource.core.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.core.jdbc-url=jdbc:mysql://127.0.0.1:3306/powerjob-daily?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.core.username=root
spring.datasource.core.password=123456
spring.datasource.core.maximum-pool-size=20
spring.datasource.core.minimum-idle=5

####### Storage properties(Delete if not needed)  #######
#oms.storage.dfs.mongodb.uri=mongodb+srv://zqq:No1Bug2Please3!@cluster0.wie54.gcp.mongodb.net/powerjob_daily?retryWrites=true&w=majority
oms.storage.dfs.mysql_series.driver=com.mysql.cj.jdbc.Driver
oms.storage.dfs.mysql_series.url=jdbc:mysql://127.0.0.1:3306/powerjob-daily?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
oms.storage.dfs.mysql_series.username=root
oms.storage.dfs.mysql_series.password=123456
oms.storage.dfs.mysql_series.auto_create_table=true

####### Email properties(Non-core configuration properties) #######
####### Delete the following code to disable the mail #######
spring.mail.host=smtp.163.com
spring.mail.username=zqq@163.com
spring.mail.password=GOFZPNARMVKCGONV
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

####### DingTalk properties(Non-core configuration properties) #######
####### Delete the following code to disable the DingTalk #######
oms.alarm.ding.app-key=dingauqwkvxxnqskknfv
oms.alarm.ding.app-secret=XWrEPdAZMPgJeFtHuL0LH73LRj-74umF2_0BFcoXMfvnX0pCQvt0rpb1JOJU_HLl
oms.alarm.ding.agent-id=847044348

####### Resource cleaning properties #######
oms.instanceinfo.retention=1
oms.container.retention.local=1
oms.container.retention.remote=-1

####### Cache properties #######
oms.instance.metadata.cache.size=1024

####### Threshold in precise fetching server(0~100). 100 means full detection of server, in which #######
####### split-brain could be avoided while performance overhead would increase. #######
oms.accurate.select.server.percentage = 50